### ISSUE TITLE
Please add me to the contributors

### ISSUE THREAD

**Issue by bimargulies** [codehaus-plexus/plexus-interpolation#1]
Could I please be a committer here? I'd like to add OSGi metadata and release.

**Comment by mcculls** [comment]
+1 for adding OSGi metadata, such as something along the lines of #2

**Comment by benson-basis** [comment]
So, @mcculls  can you add me?

**Comment by mcculls** [comment]
@bimargulies you need to talk to someone from https://github.com/orgs/codehaus-plexus/people as they own this repository

**Comment by khmarbaise** [comment]
Hi Benson, can you please check if everything is Ok? I send you an invitation...

**Comment by bimargulies** [comment]
I missed the email but now I'm in.

**Comment by bimargulies** [comment]
The pom is set to use a snapshot parent. Can we switch to a released
version so we could release?
