### ISSUE TITLE
RegexBasedInterpolatorTest fails when building with maven 3.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-interpolation#10]
Hi,
I found a problem when building the project with a apache-maven-3.4.0-SNAPSHOT:
mvn -version:
Apache Maven 3.4.0-SNAPSHOT (a2249ce21ca1e5f28858422c3018153b8eba4d3a; 2016-08-18T17:35:14-03:00)
Maven home: C:\productos\apache-maven-3.4.0-SNAPSHOT\bin..
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_66\jre
Default locale: es_AR, platform encoding: Cp1252
OS name: "Windows 10", version: "10.0", arch: "amd64", family: "Windows"

The problem is that some tests are interpolating from environment variables using ${HOME} and ${env.HOME} but this environment variable is not defined any longer inside maven 3.4.0-SNAPSHOT mvn.cmd file.
see [this commit](https://github.com/apache/maven/commit/00565ebbfbc69996450f1463644183e8f03b90b7#diff-1d3898d64b01ea4c5b609eaefeb8d6d3L35)

Setting the variable inside the mvn.cmd file corrects the problem:
`if "%HOME%" == "" (set "HOME=%USERPROFILE%")`
however I don't know if this is a bug or a feature in maven 3.4.0.

Should we change the tests to a different env var?
WDYT?
Gabriel

**Comment by michael-o** [comment]
`$HOME` is not portable. One should rely on `user.home`. I have removed this intentionally because it was an implementation detail and nothing publically documented.
Michael

**Comment by belingueres** [comment]
Thanks @michael-o .
Based on a quick search on the mvn scripts on v3.4.0-SNAPSHOT and 3.3.9, seems that environment variable MAVEN_PROJECTBASEDIR is defined in all platforms (Unix and Windows).
I that's OK I can work on a patch.

Gabriel

**Comment by michael-o** [comment]
Again, `MAVEN_PROJECTBASEDIR` is not publically documented in the header of the shell/command script, thus it is an implementation detail. You can use `JAVA_HOME` which has to exist on both platforms during `mvn test`.
