### ISSUE TITLE
Any idea what happened to the 1.23 release?

### ISSUE THREAD

**Issue by mcculls** [codehaus-plexus/plexus-interpolation#12]
The 1.23 release was prepared according to https://github.com/codehaus-plexus/plexus-interpolation/commit/c381dfe7da2de725f37b004e12403b249c1b7295 but doesn't appear on central: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/

Any chance 1.23 could be (re-)deployed or a new release made?  Would be nice to have a release that includes OSGi metadata :)  Thanks in advance

**Comment by khmarbaise** [comment]
Hi,

i recreated the release from the 1.23 tag in git. deployed it and started the sync to Central. This can take up to 4 hours or more...Apart from that the 1.23 already contains OSGi metadata in MANIFEST.MF

**Comment by mcculls** [comment]
Excellent - looks like it's reached central already: http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.23/

(it can take a bit longer to be indexed by search.maven.org)
