### ISSUE TITLE
Allow interpolation expressions which can access array, lists and maps.

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-interpolation#5]
Update ReflectionValueExtractor source code with a more up to date implementation allowing access to array, list and map elements.

This is in order to solve:
https://issues.apache.org/jira/browse/MWAR-303
which uses maven-filtering, which in turn uses plexus-interpolation.

(Will contribute a fix to this.)

TIA,
Gabriel

**Comment by khmarbaise** [comment]
Great...to hear that...
